package com.maraton.Entidades;
// Generated 19 nov. 2023 09:25:49 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Carrera generated by hbm2java
 */
@Entity
@Table(name = "carrera", schema = "public")
public class Carrera implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private short idCarrera;
	private String nombrecarrera;
	private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);

	public Carrera() {
	}

	public Carrera(short idCarrera, String nombrecarrera) {
		this.idCarrera = idCarrera;
		this.nombrecarrera = nombrecarrera;
	}

	public Carrera(short idCarrera, String nombrecarrera, Set<Estudiante> estudiantes) {
		this.idCarrera = idCarrera;
		this.nombrecarrera = nombrecarrera;
		this.estudiantes = estudiantes;
	}

	@Id

	@Column(name = "id_carrera", unique = true, nullable = false, precision = 4, scale = 0)
	public short getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(short idCarrera) {
		this.idCarrera = idCarrera;
	}

	@Column(name = "nombrecarrera", nullable = false, length = 45)
	public String getNombrecarrera() {
		return this.nombrecarrera;
	}

	public void setNombrecarrera(String nombrecarrera) {
		this.nombrecarrera = nombrecarrera;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carrera")
	public Set<Estudiante> getEstudiantes() {
		return this.estudiantes;
	}

	public void setEstudiantes(Set<Estudiante> estudiantes) {
		this.estudiantes = estudiantes;
	}

}
