package com.maraton.Entidades;
// Generated 19 nov. 2023 09:25:49 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", schema = "public")
public class Categoria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private byte idCategoria;
	private String nombre;
	private Set<EquipoCategoria> equipoCategorias = new HashSet<EquipoCategoria>(0);
	private Set<MateriaCategoria> materiaCategorias = new HashSet<MateriaCategoria>(0);

	public Categoria() {
	}

	public Categoria(byte idCategoria, String nombre) {
		this.idCategoria = idCategoria;
		this.nombre = nombre;
	}

	public Categoria(byte idCategoria, String nombre, Set<EquipoCategoria> equipoCategorias, Set<MateriaCategoria> materiaCategorias) {
		this.idCategoria = idCategoria;
		this.nombre = nombre;
		this.equipoCategorias = equipoCategorias;
		this.materiaCategorias = materiaCategorias;
	}

	@Id

	@Column(name = "id_categoria", unique = true, nullable = false, precision = 2, scale = 0)
	public byte getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(byte idCategoria) {
		this.idCategoria = idCategoria;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<EquipoCategoria> getEquipoCategorias() {
		return this.equipoCategorias;
	}

	public void setEquipoCategorias(Set<EquipoCategoria> equipoCategorias) {
		this.equipoCategorias = equipoCategorias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<MateriaCategoria> getMateriaCategorias() {
		return this.materiaCategorias;
	}

	public void setMateriaCategorias(Set<MateriaCategoria> materiaCategorias) {
		this.materiaCategorias = materiaCategorias;
	}

}
