package com.maraton.Entidades;
// Generated 19 nov. 2023 09:25:49 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Estudiante generated by hbm2java
 */
@Entity
@Table(name = "estudiante", schema = "public")
public class Estudiante implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long codigo;
	private Carrera carrera;
	private Materiaprogramacion materia;
	private Equipo equipo;
	private String nombres;

	public Estudiante() {
	}

	public Estudiante(long codigo, String nombres) {
		this.codigo = codigo;
		this.nombres = nombres;
	}

	public Estudiante(long codigo, Carrera carrera, Equipo equipo,String nombres
			) {
		this.codigo = codigo;
		this.carrera = carrera;
		this.equipo = equipo;
		this.nombres = nombres;
		
	}

	@Id

	@Column(name = "codigo", unique = true, nullable = false, precision = 12, scale = 0)
	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_carrera")
	public Carrera getCarrera() {
		return this.carrera;
	}

	public void setCarrera(Carrera carrera) {
		this.carrera = carrera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_equipo")
	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	@Column(name = "nombres", nullable = false, length = 30)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMateria")
	public Materiaprogramacion getMateria() {
		return materia;
	}

	public void setMateria(Materiaprogramacion materia) {
		this.materia = materia;
	}
	
	
}
