package com.maraton.Entidades;
// Generated 19 nov. 2023 09:25:49 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Materiaprogramacion generated by hbm2java
 */
@Entity
@Table(name = "materiaprogramacion", schema = "public")
public class Materiaprogramacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private short idMateria;
	private String nombremateria;
	private Set<Estudiante> Estudiantes = new HashSet<Estudiante>(0);
	private Set<MateriaCategoria> materiaCategorias = new HashSet<MateriaCategoria>(0);

	public Materiaprogramacion() {
	}

	public Materiaprogramacion(short idMateria, String nombremateria) {
		this.idMateria = idMateria;
		this.nombremateria = nombremateria;
	}

	public Materiaprogramacion(short idMateria,String nombremateria, Set<Estudiante> materiaEstudiantes,
			Set<MateriaCategoria> materiaCategorias) {
		this.idMateria = idMateria;
		this.nombremateria = nombremateria;
		this.materiaCategorias = materiaCategorias;
	}

	@Id

	@Column(name = "id_materia", unique = true, nullable = false, precision = 3, scale = 0)
	public short getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(short idMateria) {
		this.idMateria = idMateria;
	}

	@Column(name = "nombremateria", nullable = false, length = 45)
	public String getNombremateria() {
		return this.nombremateria;
	}

	public void setNombremateria(String nombremateria) {
		this.nombremateria = nombremateria;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "codigo")
	public Set<Estudiante> getMateriaEstudiantes() {
		return this.Estudiantes;
	}

	public void setMateriaEstudiantes(Set<Estudiante> materiaEstudiantes) {
		this.Estudiantes = materiaEstudiantes;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idMateriacat")
	public Set<MateriaCategoria> getMateriaCategorias() {
		return this.materiaCategorias;
	}

	public void setMateriaCategorias(Set<MateriaCategoria> materiaCategorias) {
		this.materiaCategorias = materiaCategorias;
	}

}
