package com.maraton.Entidades;
// Generated 19 nov. 2023 09:25:49 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * MateriaCategoria generated by hbm2java
 */
@Entity
@Table(name = "materia_categoria", schema = "public")
public class MateriaCategoria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private short idMateriacat;
	private Categoria categoria;
	private Materiaprogramacion materiaprogramacion;

	public MateriaCategoria() {
	}

	public MateriaCategoria(short idMateriacat) {
		this.idMateriacat = idMateriacat;
	}

	public MateriaCategoria(short idMateriacat, Categoria categoria, Materiaprogramacion materiaprogramacion) {
		this.idMateriacat = idMateriacat;
		this.categoria = categoria;
		this.materiaprogramacion = materiaprogramacion;
	}

	@Id

	@Column(name = "id_materiacat", unique = true, nullable = false, precision = 3, scale = 0)
	public short getIdMateriacat() {
		return this.idMateriacat;
	}

	public void setIdMateriacat(short idMateriacat) {
		this.idMateriacat = idMateriacat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_categoria")
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	public Materiaprogramacion getMateriaprogramacion() {
		return this.materiaprogramacion;
	}

	public void setMateriaprogramacion(Materiaprogramacion materiaprogramacion) {
		this.materiaprogramacion = materiaprogramacion;
	}

}
